MODEL:
  BACKBONE:
    FREEZE_AT: 5
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [ 129.29800347, 123.72804303, 112.17488163 ]
  PIXEL_STD: [ 56.38888476, 56.37252828, 55.57643895 ]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
    # NORM: "BN"
    RES5_MULTI_GRID: [ 1, 1, 1 ]  # not used
DATASETS:
  TRAIN: ("ade_indoor_sem_seg_train",)
  TEST: ("ade_indoor_sem_seg_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0005
  BASE_LR_END: 1e-6
  MAX_ITER: 500
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval [ "[int(x * 0.1 * 512) for x in range(5, 21)]" ]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
  MASK_FORMAT: "L"
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 512  # used in dataset mapper
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 500
  AUG:
    ENABLED: True
    MIN_SIZES: [ 256, 384, 512, 640, 768, 896 ]
    MAX_SIZE: 2048
    FLIP: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2
LOSS:
  NAME: [ "labels", "masks", "edge" ]